/**
 * Curated playable fine positions for famous players where Transfermarkt's single primary
 * sub_position is incomplete (multi-position stars) or missing (legends the DOB ingest missed).
 *
 * Each entry: [display name, nationality, all fine positions the player may fill in-game].
 * The apply job merges these into players.sub_positions (and sets sub_position when null).
 */
export const POSITION_OVERRIDES: Array<[string, string, string[]]> = [
  // Multi-position fame — primary TM value kept; alternates added.
  ['Cristiano Ronaldo', 'Portugal', ['Centre-Forward', 'Right Winger']],
  ['Gareth Bale', 'Wales', ['Left Winger', 'Right Winger']],
  ['Thierry Henry', 'France', ['Centre-Forward', 'Left Winger']],
  ['Luís Figo', 'Portugal', ['Right Winger', 'Right Midfield']],
  ['Dennis Bergkamp', 'Netherlands', ['Second Striker', 'Attacking Midfield']],
  ['Rivaldo', 'Brazil', ['Attacking Midfield', 'Left Winger']],
  ['Ronaldinho', 'Brazil', ['Attacking Midfield', 'Left Winger']],
  ['Roberto Firmino', 'Brazil', ['Centre-Forward', 'Attacking Midfield']],
  ['Karim Benzema', 'France', ['Centre-Forward', 'Attacking Midfield']],
  ['Mohamed Salah', 'Egypt', ['Right Winger', 'Centre-Forward']],
  ['Son Heung-min', 'South Korea', ['Left Winger', 'Centre-Forward']],
  ['Kylian Mbappé', 'France', ['Left Winger', 'Centre-Forward']],
  ['Neymar', 'Brazil', ['Left Winger', 'Attacking Midfield']],
  ['Lionel Messi', 'Argentina', ['Right Winger', 'Attacking Midfield', 'Centre-Forward']],

  // Tier-5 legends missing sub_position from TM ingest.
  ['Paolo Maldini', 'Italy', ['Centre-Back']],
  ['Franco Baresi', 'Italy', ['Centre-Back']],
  ['Alessandro Nesta', 'Italy', ['Centre-Back']],
  ['Fabio Cannavaro', 'Italy', ['Centre-Back']],
  ['Alessandro Costacurta', 'Italy', ['Centre-Back']],
  ['Ciro Ferrara', 'Italy', ['Centre-Back']],
  ['Mark Iuliano', 'Italy', ['Centre-Back']],
  ['Paolo Montero', 'Uruguay', ['Centre-Back']],
  ['Mauricio Pellegrino', 'Argentina', ['Centre-Back']],
  ['Fernando Hierro', 'Spain', ['Centre-Back']],
  ['Iván Helguera', 'Spain', ['Centre-Back']],
  ['Marcel Desailly', 'France', ['Centre-Back']],
  ['Thomas Linke', 'Germany', ['Centre-Back']],
  ['Cafú', 'Brazil', ['Right-Back']],
  ['Roberto Carlos', 'Brazil', ['Left-Back']],
  ['Bixente Lizarazu', 'France', ['Left-Back']],
  ['Christian Panucci', 'Italy', ['Right-Back']],
  ['Gianluca Pessotto', 'Italy', ['Right-Back']],
  ['Markus Babbel', 'Germany', ['Right-Back']],
  ['Míchel Salgado', 'Spain', ['Right-Back']],
  ['Jocelyn Angloma', 'France', ['Right-Back']],
  ['Lilian Thuram', 'France', ['Right-Back', 'Centre-Back']],
  ['Dani Carvajal', 'Spain', ['Right-Back']],
  ['Angelo Peruzzi', 'Italy', ['Goalkeeper']],
  ['Edwin van der Sar', 'Netherlands', ['Goalkeeper']],
  ['Fabien Barthez', 'France', ['Goalkeeper']],
  ['Frank Boer', 'Netherlands', ['Goalkeeper']],
  ['Oliver Kahn', 'Germany', ['Goalkeeper']],
  ['Jens Lehmann', 'Germany', ['Goalkeeper']],
  ['Santiago Cañizares', 'Spain', ['Goalkeeper']],
  ['Claude Makelele', 'France', ['Defensive Midfield']],
  ['Patrick Vieira', 'France', ['Defensive Midfield']],
  ['Didier Deschamps', 'France', ['Defensive Midfield']],
  ['Edgar Davids', 'Netherlands', ['Defensive Midfield']],
  ['Gennaro Gattuso', 'Italy', ['Defensive Midfield']],
  ['Dietmar Hamann', 'Germany', ['Defensive Midfield']],
  ['Frank Rijkaard', 'Netherlands', ['Defensive Midfield', 'Centre-Back']],
  ['Alessio Tacchinardi', 'Italy', ['Defensive Midfield']],
  ['Michael Ballack', 'Germany', ['Central Midfield']],
  ['Torsten Frings', 'Germany', ['Central Midfield']],
  ['Demetrio Albertini', 'Italy', ['Central Midfield']],
  ['Antonio Conte', 'Italy', ['Central Midfield']],
  ['Clarence Seedorf', 'Netherlands', ['Central Midfield', 'Attacking Midfield']],
  ['Deco', 'Portugal', ['Attacking Midfield']],
  ['Zinédine Zidane', 'France', ['Attacking Midfield']],
  ['Bernd Schuster', 'Germany', ['Attacking Midfield']],
  ['Mehmet Scholl', 'Germany', ['Attacking Midfield']],
  ['Jari Litmanen', 'Finland', ['Attacking Midfield']],
  ['Pavel Nedvěd', 'Czech Republic', ['Left Midfield']],
  ['Robert Pirès', 'France', ['Left Winger']],
  ['Sylvain Wiltord', 'France', ['Left Winger']],
  ['Hristo Stoichkov', 'Bulgaria', ['Left Winger']],
  ['Roberto Donadoni', 'Italy', ['Right Midfield']],
  ['Angelo Livio', 'Italy', ['Right Midfield']],
  ['Hasan Salihamidžić', 'Bosnia and Herzegovina', ['Right Midfield']],
  ['Alessandro Del Piero', 'Italy', ['Second Striker', 'Attacking Midfield']],
  ['Andriy Shevchenko', 'Ukraine', ['Centre-Forward']],
  ['Filippo Inzaghi', 'Italy', ['Centre-Forward']],
  ['David Trézéguet', 'France', ['Centre-Forward']],
  ['Davor Šuker', 'Croatia', ['Centre-Forward']],
  ['Daniele Massaro', 'Italy', ['Centre-Forward']],
  ['Fernando Morientes', 'Spain', ['Centre-Forward']],
  ['Henrik Larsson', 'Sweden', ['Centre-Forward']],
  ['Mário Jardel', 'Brazil', ['Centre-Forward']],
  ['Diego Forlán Corazo', 'Uruguay', ['Centre-Forward', 'Second Striker']],
  ['Nwankwo Kanu', 'Nigeria', ['Second Striker']],
  ['Marco Basten', 'Netherlands', ['Centre-Forward']],
];
