/**
 * Fine-position backfill for tier-4+ players the TM ingest missed (no DOB match, no external_id, etc.).
 * Keyed by name + nationality with optional externalId / birthDate to disambiguate duplicates.
 */
export interface PositionBackfillEntry {
  name: string;
  nationality: string;
  positions: string[];
  externalId?: string;
  birthDate?: string;
  externalIdIsNull?: boolean;
  birthDateIsNull?: boolean;
}

export const POSITION_BACKFILL: PositionBackfillEntry[] = [
  { name: 'Adam Wharton', nationality: 'England', positions: ['Central Midfield', 'Defensive Midfield'], externalId: '288102' },
  { name: 'Nuno Mendes', nationality: 'Portugal', positions: ['Left-Back'], externalId: '263482' },
  { name: 'Nuno Mendes', nationality: 'Portugal', positions: ['Left-Back'], birthDate: '1979-12-06' },
  { name: 'Rodri', nationality: 'Spain', positions: ['Defensive Midfield'], externalId: '44' },
  { name: 'Alain Boghossian', nationality: 'France', positions: ['Central Midfield'] },
  { name: 'Albert Ferrer', nationality: 'Spain', positions: ['Right-Back'] },
  { name: 'Aldair', nationality: 'Brazil', positions: ['Centre-Back'] },
  { name: 'Alen Bokšić', nationality: 'Croatia', positions: ['Centre-Forward'] },
  { name: 'Alessandro Birindelli', nationality: 'Italy', positions: ['Right-Back'] },
  { name: 'Alexander Hleb', nationality: 'Belarus', positions: ['Left Winger', 'Attacking Midfield'] },
  { name: 'Alexander Zickler', nationality: 'Germany', positions: ['Centre-Forward'] },
  { name: 'Amedeo Carboni', nationality: 'Italy', positions: ['Left-Back'] },
  { name: 'Andy Robertson', nationality: 'Unknown', positions: ['Left-Back'], birthDate: '1994-03-11' },
  { name: 'Ángel María', nationality: 'Argentina', positions: ['Right Winger', 'Attacking Midfield'] },
  { name: 'Angelos Basinas', nationality: 'Greece', positions: ['Defensive Midfield'], externalId: '113866' },
  { name: 'Antonio Puerta', nationality: 'Spain', positions: ['Left-Back', 'Left Winger'] },
  { name: 'Antonios Nikopolidis', nationality: 'Greece', positions: ['Goalkeeper'] },
  { name: 'Arif Erdem', nationality: 'Turkey', positions: ['Centre-Forward'] },
  { name: 'Bernd Schneider', nationality: 'Germany', positions: ['Attacking Midfield', 'Central Midfield'] },
  { name: 'Boris Živković', nationality: 'Croatia', positions: ['Centre-Back'] },
  { name: 'Boudewijn Zenden', nationality: 'Netherlands', positions: ['Left Midfield', 'Left Winger'], externalId: '115945' },
  { name: 'Brahim Hemdani', nationality: 'Algeria', positions: ['Defensive Midfield'] },
  { name: 'Bülent Korkmaz', nationality: 'Turkey', positions: ['Centre-Back'] },
  { name: 'Capucho', nationality: 'Portugal', positions: ['Left Winger'] },
  { name: 'Carsten Jancker', nationality: 'Germany', positions: ['Centre-Forward'] },
  { name: 'Carsten Ramelow', nationality: 'Germany', positions: ['Defensive Midfield'] },
  { name: 'Christian Karembeu', nationality: 'France', positions: ['Right Midfield'] },
  { name: 'Christian Ziege', nationality: 'Germany', positions: ['Left-Back'] },
  { name: 'Christophe Dugarry', nationality: 'France', positions: ['Centre-Forward'] },
  { name: 'Cláudio Taffarel', nationality: 'Brazil', positions: ['Goalkeeper'] },
  { name: 'Costinha', nationality: 'Portugal', positions: ['Defensive Midfield'] },
  { name: 'Danny Blind', nationality: 'Netherlands', positions: ['Centre-Back', 'Defensive Midfield'] },
  { name: 'Danny Murphy', nationality: 'England', positions: ['Central Midfield'], externalId: '114866' },
  { name: 'David Seaman', nationality: 'England', positions: ['Goalkeeper'] },
  { name: 'Dejan Savićević', nationality: 'Yugoslavia', positions: ['Attacking Midfield'] },
  { name: 'Dejan Stankovic', nationality: 'Serbia', positions: ['Central Midfield', 'Attacking Midfield'], externalId: '115300' },
  { name: 'Denílson', nationality: 'Brazil', positions: ['Left Winger'] },
  { name: 'Denis Irwin', nationality: 'Republic of Ireland', positions: ['Right-Back', 'Left-Back'] },
  { name: 'Derlei', nationality: 'Brazil', positions: ['Centre-Forward'] },
  { name: 'Diego Fuser', nationality: 'Italy', positions: ['Right Midfield'] },
  { name: 'Dino Baggio', nationality: 'Italy', positions: ['Central Midfield'] },
  { name: 'Dmitri Alenichev', nationality: 'Russia', positions: ['Central Midfield'] },
  { name: 'Dunga', nationality: 'Unknown', positions: ['Defensive Midfield'], birthDate: '1963-10-31' },
  { name: 'Edmílson', nationality: 'Brazil', positions: ['Defensive Midfield', 'Centre-Back'], externalId: '115875' },
  { name: 'Edouard Cissé', nationality: 'France', positions: ['Defensive Midfield'], externalId: '113807' },
  { name: 'Emerson', nationality: 'Brazil', positions: ['Left-Back'] },
  { name: 'Emmanuel Petit', nationality: 'France', positions: ['Defensive Midfield'] },
  { name: 'Ergün Penbe', nationality: 'Turkey', positions: ['Left Winger'] },
  { name: 'Evanilson', nationality: 'Brazil', positions: ['Centre-Back'], birthDateIsNull: true },
  { name: 'Fábio Rochemback', nationality: 'Brazil', positions: ['Central Midfield'] },
  { name: 'Fábio Tavares', nationality: 'Brazil', positions: ['Left Winger'], externalId: '299' },
  { name: 'Fernando Redondo', nationality: 'Argentina', positions: ['Defensive Midfield'] },
  { name: 'Finidi George', nationality: 'Nigeria', positions: ['Right Winger'] },
  { name: 'Francesco Toldo', nationality: 'Italy', positions: ['Goalkeeper'] },
  { name: 'Francisco Lima', nationality: 'Brazil', positions: ['Defensive Midfield'] },
  { name: 'Francisco Rufete', nationality: 'Spain', positions: ['Right Midfield'], externalId: '117097' },
  { name: 'Freddie Ljungberg', nationality: 'Sweden', positions: ['Right Midfield'] },
  { name: 'Frédéric Kanouté', nationality: 'Mali', positions: ['Centre-Forward'], externalId: '117003' },
  { name: 'Gaizka Mendieta', nationality: 'Spain', positions: ['Attacking Midfield', 'Central Midfield'] },
  { name: 'Gary Neville', nationality: 'England', positions: ['Right-Back'], externalId: '115961' },
  { name: 'Gerard López', nationality: 'Spain', positions: ['Attacking Midfield'] },
  { name: 'Gianluca Pagliuca', nationality: 'Italy', positions: ['Goalkeeper'] },
  { name: 'Gianluca Zambrotta', nationality: 'Italy', positions: ['Right-Back'], externalId: '115361' },
  { name: 'Gianluigi Lentini', nationality: 'Italy', positions: ['Right Winger'] },
  { name: 'Gilberto Silva', nationality: 'Brazil', positions: ['Defensive Midfield'] },
  { name: 'Giovane Élber', nationality: 'Brazil', positions: ['Centre-Forward'] },
  { name: 'Giovanni Bronckhorst', nationality: 'Netherlands', positions: ['Left-Back'] },
  { name: 'Giuseppe Favalli', nationality: 'Italy', positions: ['Centre-Back', 'Left-Back'] },
  { name: 'Guti', nationality: 'Spain', positions: ['Attacking Midfield'] },
  { name: 'Hakan Şükür', nationality: 'Turkey', positions: ['Centre-Forward'] },
  { name: 'Hans-Jörg Butt', nationality: 'Germany', positions: ['Goalkeeper'], externalId: '115053' },
  { name: 'Harry Kewell', nationality: 'Australia', positions: ['Left Winger'] },
  { name: 'Hasan Şaş', nationality: 'Turkey', positions: ['Right Winger'] },
  { name: 'Hernán Crespo', nationality: 'Argentina', positions: ['Centre-Forward'], externalId: '115363' },
  { name: 'Jaap Stam', nationality: 'Netherlands', positions: ['Centre-Back'] },
  { name: 'Jean-Pierre Papin', nationality: 'France', positions: ['Centre-Forward'] },
  { name: 'Jens Jeremies', nationality: 'Germany', positions: ['Defensive Midfield'] },
  { name: 'Jerzy Dudek', nationality: 'Poland', positions: ['Goalkeeper'], externalId: '117093' },
  { name: 'John Carew', nationality: 'Norway', positions: ['Centre-Forward'], externalId: '115943' },
  { name: 'Jon Tomasson', nationality: 'Denmark', positions: ['Centre-Forward'] },
  { name: 'Jorge Costa', nationality: 'Portugal', positions: ['Centre-Back'] },
  { name: 'Jörg Heinrich', nationality: 'Germany', positions: ['Left-Back'] },
  { name: 'José Martí', nationality: 'Spain', positions: ['Right Winger'], externalId: '116938' },
  { name: 'José Reyes', nationality: 'Spain', positions: ['Left Winger'] },
  { name: 'Juan Verón', nationality: 'Argentina', positions: ['Attacking Midfield'] },
  { name: 'Juliano Belletti', nationality: 'Brazil', positions: ['Right-Back'] },
  { name: 'Jürgen Klinsmann', nationality: 'Germany', positions: ['Centre-Forward'] },
  { name: 'Jürgen Kohler', nationality: 'Germany', positions: ['Centre-Back'] },
  { name: 'Kakha Kaladze', nationality: 'Georgia', positions: ['Centre-Back'] },
  { name: 'Kily González', nationality: 'Argentina', positions: ['Left Winger'] },
  { name: 'Lars Ricken', nationality: 'Germany', positions: ['Attacking Midfield'] },
  { name: 'Laurent Blanc', nationality: 'France', positions: ['Centre-Back'] },
  { name: 'Lothar Matthäus', nationality: 'Germany', positions: ['Defensive Midfield', 'Centre-Back'] },
  { name: 'Luis Alberto', nationality: 'Spain', positions: ['Attacking Midfield'], externalId: '117092' },
  { name: 'Luís Fabiano', nationality: 'Brazil', positions: ['Centre-Forward'], externalId: '80394' },
  { name: 'Luiz Dias', nationality: 'Brazil', positions: ['Central Midfield'], externalId: '1909' },
  { name: 'Maniche', nationality: 'Portugal', positions: ['Left Midfield'] },
  { name: 'Manolo Sanchís', nationality: 'Spain', positions: ['Centre-Back'] },
  { name: 'Marco Bode', nationality: 'Germany', positions: ['Left Winger'] },
  { name: 'Marco Materazzi', nationality: 'Italy', positions: ['Centre-Back'], externalId: '115444' },
  { name: 'Marco Simone', nationality: 'Italy', positions: ['Centre-Forward'] },
  { name: 'Marc Overmars', nationality: 'Netherlands', positions: ['Left Winger'] },
  { name: 'Matthias Sammer', nationality: 'Germany', positions: ['Centre-Back', 'Defensive Midfield'] },
  { name: 'Mauro Camoranesi', nationality: 'Italy', positions: ['Right Midfield'], externalId: '115079' },
  { name: 'Mauro Silva', nationality: 'Brazil', positions: ['Defensive Midfield'] },
  { name: 'Mauro Tassotti', nationality: 'Italy', positions: ['Right-Back'] },
  { name: 'Michael Reiziger', nationality: 'Netherlands', positions: ['Right-Back'] },
  { name: 'Michael Tarnat', nationality: 'Germany', positions: ['Left-Back'] },
  { name: 'Miguel Angulo', nationality: 'Spain', positions: ['Right Winger'] },
  { name: 'Miguel Nadal', nationality: 'Spain', positions: ['Centre-Back'] },
  { name: 'Mikaël Silvestre', nationality: 'France', positions: ['Centre-Back'], externalId: '115062' },
  { name: 'Miroslav Đukić', nationality: 'Serbia', positions: ['Centre-Back'] },
  { name: 'Moreno Torricelli', nationality: 'Italy', positions: ['Right-Back'] },
  { name: 'Mykhailo Mudryk', nationality: 'Ukraine', positions: ['Left Winger'], externalId: '63577' },
  { name: 'Nicky Butt', nationality: 'England', positions: ['Central Midfield'] },
  { name: 'Ole Solskjær', nationality: 'Norway', positions: ['Centre-Forward'] },
  { name: 'Oliver Bierhoff', nationality: 'Germany', positions: ['Centre-Forward'] },
  { name: 'Oliver Neuville', nationality: 'Germany', positions: ['Centre-Forward', 'Second Striker'] },
  { name: 'Owen Hargreaves', nationality: 'England', positions: ['Defensive Midfield', 'Central Midfield'], externalId: '114895' },
  { name: 'Patrick Kluivert', nationality: 'Netherlands', positions: ['Centre-Forward'] },
  { name: 'Patrik Berger', nationality: 'Czech Republic', positions: ['Attacking Midfield'] },
  { name: 'Paul Lambert', nationality: 'Scotland', positions: ['Central Midfield'] },
  { name: 'Paulo Sousa', nationality: 'Portugal', positions: ['Central Midfield'], birthDate: '1970-08-30' },
  { name: 'Pedro Emanuel', nationality: 'Portugal', positions: ['Centre-Back'] },
  { name: 'Pep Guardiola', nationality: 'Spain', positions: ['Defensive Midfield'] },
  { name: 'Peter Schmeichel', nationality: 'Denmark', positions: ['Goalkeeper'] },
  { name: 'Phillip Cocu', nationality: 'Netherlands', positions: ['Central Midfield'] },
  { name: 'Predrag Mijatović', nationality: 'Serbia', positions: ['Left Winger', 'Attacking Midfield'] },
  { name: 'Radamel Falcao', nationality: 'Colombia', positions: ['Centre-Forward'], externalId: '119' },
  { name: 'Radamel Falcao', nationality: 'Colombia', positions: ['Centre-Forward'], birthDate: '1986-02-10', externalIdIsNull: true },
  { name: 'Raúl', nationality: 'Spain', positions: ['Centre-Forward', 'Second Striker'], externalId: '115023' },
  { name: 'Roberto Ayala', nationality: 'Argentina', positions: ['Centre-Back'] },
  { name: 'Roberto Baggio', nationality: 'Italy', positions: ['Attacking Midfield', 'Second Striker'] },
  { name: 'Romário', nationality: 'Brazil', positions: ['Centre-Forward'] },
  { name: 'Ronald Boer', nationality: 'Netherlands', positions: ['Right Winger'] },
  { name: 'Roque Júnior', nationality: 'Brazil', positions: ['Centre-Back'] },
  { name: 'Roy Makaay', nationality: 'Netherlands', positions: ['Centre-Forward'] },
  { name: 'Rubén Baraja', nationality: 'Spain', positions: ['Central Midfield'] },
  { name: 'Ruud Gullit', nationality: 'Netherlands', positions: ['Attacking Midfield'] },
  { name: 'Sami Hyypia', nationality: 'Finland', positions: ['Centre-Back'], externalId: '115080' },
  { name: 'Samuel Kuffour', nationality: 'Ghana', positions: ['Centre-Back'] },
  { name: 'Sebastiano Rossi', nationality: 'Italy', positions: ['Goalkeeper'] },
  { name: 'Sergei Ignashevich', nationality: 'Russia', positions: ['Centre-Back'] },
  { name: 'Sergi Barjuán', nationality: 'Spain', positions: ['Left-Back'] },
  { name: 'Serginho', nationality: 'Brazil', positions: ['Left-Back'] },
  { name: 'Sol Campbell', nationality: 'England', positions: ['Centre-Back'], externalId: '115950' },
  { name: 'Stefan Effenberg', nationality: 'Germany', positions: ['Central Midfield'] },
  { name: 'Stefan Klos', nationality: 'Germany', positions: ['Goalkeeper'] },
  { name: 'Stefano Eranio', nationality: 'Italy', positions: ['Right Midfield'] },
  { name: 'Stefano Fiore', nationality: 'Italy', positions: ['Second Striker', 'Attacking Midfield'] },
  { name: 'Stefan Reuter', nationality: 'Germany', positions: ['Right-Back'] },
  { name: 'Steve Finnan', nationality: 'Republic of Ireland', positions: ['Right-Back'] },
  { name: 'Steve McManaman', nationality: 'England', positions: ['Right Midfield'] },
  { name: 'Sylvinho', nationality: 'Brazil', positions: ['Left-Back'] },
  { name: 'Thorsten Fink', nationality: 'Germany', positions: ['Central Midfield'] },
  { name: 'Tyler Dibling', nationality: 'England', positions: ['Right Winger'], externalId: '304317' },
  { name: 'Ümit Davala', nationality: 'Turkey', positions: ['Right Midfield'] },
  { name: 'Vítor Baía', nationality: 'Portugal', positions: ['Goalkeeper'] },
  { name: 'Vladimir Jugović', nationality: 'Serbia', positions: ['Defensive Midfield'] },
  { name: 'Vladimír Šmicer', nationality: 'Czech Republic', positions: ['Right Midfield'] },
  { name: 'Walter Pandiani', nationality: 'Uruguay', positions: ['Centre-Forward'], externalId: '117006' },
  { name: 'Willy Sagnol', nationality: 'France', positions: ['Right-Back'] },
  { name: 'Youri Djorkaeff', nationality: 'France', positions: ['Attacking Midfield'] },
  { name: 'Zvonimir Boban', nationality: 'Croatia', positions: ['Central Midfield'] },
];
